#!/usr/bin/env python3
"""
Upload candidates from parsed_candidates.json into Supabase.

Usage (from this directory):

    SUPABASE_URL="..." SUPABASE_KEY="..." python3 upload_candidates.py

Input:
- parsed_candidates.json (generated by preprocess_written.py in this directory)
"""

import json
import os

from supabase import Client, create_client

try:
    from dotenv import load_dotenv

    # Load env from repo root and frontend .env
    load_dotenv()
    load_dotenv("frontend/.env")
except ImportError:
    pass


def upload_candidates(json_path: str) -> None:
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_KEY")

    if not url or not key:
        print("\n❌ Error: SUPABASE_URL and SUPABASE_KEY not found.")
        print("-" * 50)
        print("I couldn't find your Supabase credentials in environment variables or your .env file.")
        print("\nPlease run the command like this:")
        print('SUPABASE_URL="..." SUPABASE_KEY="..." python3 upload_candidates.py')
        print("-" * 50)
        return

    supabase: Client = create_client(url, key)

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            candidates = json.load(f)
    except FileNotFoundError:
        print(f"Error: Could not find {json_path}. Please run preprocess_written.py first.")
        return

    candidate_columns = {
        "email",
        "first_name",
        "last_name",
        "full_name",
        "school",
        "class_year",
        "major",
        "nationality",
        "candidate_type",
        "seminar_title",
        "seminar_category",
        "seminar_description",
        "final_product",
        "more_topics",
        "interest_reason",
        "teaching_exp",
        "advice",
        "self_intro",
        "grader_name",
        "tier_level",
        "written_score_interest",
        "written_score_teaching",
        "written_score_seminar",
        "written_score_personal",
        "availability",
        "fly_from",
        "fly_to",
        "sensitive_issues",
        "score_understanding",
        "score_enthusiasm",
        "score_quality",
        "score_teaching",
        "score_interest",
        "score_overall",
        "score_empirical",
        "deliberation_status",
    }

    print(f"Uploading {len(candidates)} candidates to Supabase...")

    batch_size = 100
    for i in range(0, len(candidates), batch_size):
        raw_batch = candidates[i : i + batch_size]

        batch = [{k: v for k, v in cand.items() if k in candidate_columns} for cand in raw_batch]

        try:
            supabase.table("candidates").insert(batch).execute()
            print(f"Successfully inserted batch {i // batch_size + 1}")
        except Exception as e:  # noqa: BLE001
            print(f"Error inserting batch {i // batch_size + 1}: {e}")

    print("Done!")


if __name__ == "__main__":
    repo_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(repo_dir, "parsed_candidates.json")
    upload_candidates(json_path)

